language: minimal

env:
    - APP_NAME=travis-ci-testdrive

services:
    - docker

install:
    - docker build -t $APP_NAME:$TRAVIS_BUILD_ID .

after_success:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - eval $(aws ecr get-login --no-include-email --region us-east-1)
    - docker tag $APP_NAME:$TRAVIS_BUILD_ID $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$APP_NAME:$TRAVIS_BUILD_ID
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$APP_NAME:$TRAVIS_BUILD_ID
